### ISSUE TITLE
Data Loader fails to build

### ISSUE THREAD

**Issue by landonconover** [instructure/canvas-data-loader#4]
### Description ###

When I run 'cargo build --release' I get the following error:

`error[E0599]: no method named `expect` found for type `()` in the current scope
  --> src/main.rs:57:22
   |
57 |   env_logger::init().expect("Failed to setup logger!");
   |                      ^^^^^^

error: aborting due to previous error

error: Could not compile `cdl-runner`.`

I am not proficient in rust and am not sure where to start debugging.

Thanks in advance for any help.

### Additional Information ###

* Rust Version: rustc 1.23.0 (766bd11c8 2018-01-01)
* Platform: Mac running OS version 10.13.2
* Logs: I can't run the app with debug info since the issue is in the compile phase. Attached
 is the output of cargo build --release --verbose
[Verbose Output.txt](https://github.com/instructure/canvas-data-loader/files/1687527/Verbose.Output.txt)

**Comment by SecurityInsanity** [comment]
Hey @landonconover ,

Sorry about this. It turns out lately certain dependencies that hadn't changed in years finally started changing, and broke in our assumptions (thus causing the code not to compile). So I've not only updated the dependency that was causing this particular problem, but I've also pinned every single dependency so that way hopefully we get hit by as few breaking changes as possible.

Sorry about our assumptions causing pain like this!

**Comment by landonconover** [comment]
Thanks a bunch! Glad I was able to help.
